### ISSUE TITLE
Investigate if Web App should be migrated to react app

### ISSUE THREAD

**Issue by andreamorales** [GetPanto/MPEG-21-Part-23-Webapp#4]

**Comment by kangarang** [comment]
we've decided to migrate the existing code to a react app.

the current demo site code is stale, cluttered, and uses only vanilla javascript and html. migrating the code to typescript and react will not only make the code stronger, but it will also make it easier for all current and future developers to refactor and review.

we will:
- use current demo site copy and layout as a guide for acceptance criteria (completion)
- refactor stale code to use the latest best practices and tools
- gut out and reorganize the usable functions into utils and hooks
- create simple, reusable react components to present data and user interactions
